// const { describe } = require("mocha");

describe("tasks for students", () => {
    // it("tasks", () => {
    //     cy.visit("https://dev02.speechpundit.com")
    //     cy.wait(5000);
    //     cy.get('.d-none > .btn').click()
    //     cy.get('.log').click()
    //     cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
    //     cy.get(':nth-child(2) > .form-control').type("luckysai")
    //     cy.get('[style="text-align: center;"] > .btn').type("{enter}")
    //     cy.get('[href="/user"]').click()
    //     cy.get('[href="/user/lessonplan"]').click().trigger("mouseout")
    //     cy.get('.btn-icon').click()
    //     cy.get('form > :nth-child(3)').click()
    //     cy.get(':nth-child(1) > .col > .position-relative > #validationStandard01').type("environment")
    //     cy.get(':nth-child(2) > .col > .position-relative > #validationStandard01').type("about environment")
    //     cy.get('#validationStandard02').select("Beginner")
    //     cy.get('.ml-auto').click().wait(4000)
    //     cy.get('#validationStandard03').type("5")
    //     cy.get('form > .btn').click()
    //     cy.get('.btn-icon').click()
    //     cy.get('form > :nth-child(3)').click()
    //     cy.get(':nth-child(1) > .col > .position-relative > #validationStandard01').type("Rasism")
    //     cy.get(':nth-child(2) > .col > .position-relative > #validationStandard01').type("about Rasism")
    //     cy.get('#validationStandard02').select("Beginner")
    //     cy.get('.ml-auto').click().wait(4000)
    //     cy.get('#validationStandard03').type("5")
    //     cy.get('form > .btn').click()
    // })
    // it("groups tasks", () => {
    //     cy.visit("https://dev02.speechpundit.com")
    //     cy.wait(5000)
    //     cy.get(':nth-child(6) > .nav-link').click()
    //     cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
    //     cy.get(':nth-child(2) > .form-control').type("luckysai")
    //     cy.get('[style="text-align: center;"] > .btn').click()
    //     cy.get('[href="/user"]').click()
    //     cy.get('[href="/user/groups"]').click().trigger("mouseout")
    //     // cy.get('.btn-icon > span').click()
    //     cy.get('.mb-3 > a').click()
    //     // cy.get('.mb-3 > a').click()
    //     cy.get('#controlled-tab-example-tab-classwork').click()
    //     // Select the button by class and text content// Select the button by type and class
    //     // Select the button by the presence of an `svg` element
    //     // Select the button by its attributes and the presence of the `span` element
    //     cy.get('button[type="button"].btn-icon-start:contains("Add Assignment")').click({force:true});
    //     cy.get('#formHorizontalLevel').select("environment")
    //     cy.get('#controlled-tab-example-tabpane-addassignment > form > .g-3 > :nth-child(2) > .col-sm-10 > #startdate').type("2023-09-27")
    //     // cy.get('#controlled-tab-example-tabpane-addassignment > form > .g-3 > :nth-child(3) > .col-sm-10 > #startdate').type
    //     cy.get('#enddate').type("2023-09-29")
    //     cy.get('#selectstudent > .p-multiselect-label-container > .p-multiselect-label').click()
    //     // cy.get('.p-multiselect-header > .p-checkbox > .p-checkbox-box').check()
    //     cy.get('.p-multiselect-header > .p-checkbox > .p-checkbox-box').click()
    //     cy.get('.p-multiselect-close').click()
    //     cy.get('#controlled-tab-example-tabpane-addassignment > form > .float-right').click()
    // })
    // it("vocal assignment",()=>{
    //     cy.visit("https://dev02.speechpundit.com")
    //     cy.wait(5000)
    //     cy.get(':nth-child(6) > .nav-link').click()
    //     cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
    //     cy.get(':nth-child(2) > .form-control').type("luckysai")
    //     cy.get('[style="text-align: center;"] > .btn').click()
    //     cy.get('[href="/user"]').click()
    //     cy.get('[href="/user/groups"]').click().trigger("mouseout")
    //     cy.get('.mb-3 > a').click()
    //     cy.get('#controlled-tab-example-tab-classwork').click()
    //     cy.get('button[type="button"].btn-icon-start:contains("Add Assignment")').click({force:true})
    //     cy.get('#controlled-tab-example-tab-vocalassignment').click()
    //     cy.get(':nth-child(3) > .form-check-label > .radio-position').click()
    //     cy.get('#controlled-tab-example-tabpane-vocalassignment > form > .g-3 > :nth-child(2) > .col-sm-10 > #startdate').type("2023-09-27")
    //     cy.get('[placeholder="end date"]').type("2023-09-27")
    //     cy.get('#controlled-tab-example-tabpane-vocalassignment > form > .g-3 > :nth-child(4) > .col-sm-10 > .p-multiselect > .p-multiselect-label-container > .p-multiselect-label').click()
    //     cy.get('.p-multiselect-header > .p-checkbox > .p-checkbox-box').click()
    //     cy.get('.p-multiselect-close-icon').click()
    //     cy.get('#controlled-tab-example-tabpane-vocalassignment > form > .float-right').click()
    // })
        it("impromptu",()=>{
            cy.visit("https://dev02.speechpundit.com")
            cy.wait(5000)
            cy.get(':nth-child(6) > .nav-link').click()
            cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
            cy.get(':nth-child(2) > .form-control').type("luckysai")
            cy.get('[style="text-align: center;"] > .btn').click()
            cy.get('[href="/user"]').click()
            cy.get('[href="/user/impromptu"]').click().trigger("mouseout")
            cy.get(':nth-child(2) > .btn-icon').click()
            cy.get(':nth-child(5) > .accordion > .accordion-item > .accordion-header > .accordion-button').click()
            cy.get(':nth-child(5) > .accordion > .accordion-item > :nth-child(6) > .accordion-collapse > .accordion-body > [style="padding-right: 15px; color: red;"] > .form-check-input').click()
            cy.get('.mt-3').click()
            cy.get(':nth-child(1) > .btn-icon').click()
            cy.get(':nth-child(2) > .g-2 > :nth-child(2) > .dcard > :nth-child(5)').click()
            cy.go("back")
        })
})