describe("speech pundit", () => {//part of mocha test framework(testing framework cypress).used for organizing testcases into suites or groups
//     it("speechpundit login", () => {//it indicate individual test case
//         cy.visit("https://dev02.speechpundit.com")
//         cy.wait(5000);
//         cy.get('.d-none > .btn').click()
//         cy.get('.log').click()
//         cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
//         cy.get(':nth-child(2) > .form-control').type("luckysai")
//         cy.get('[style="text-align: center;"] > .btn').type("{enter}")
//         // cy.get('[style="text-align: center;"] > .btn').click()
//         cy.get('[href="/user"]').click()
//         cy.get('[href="/user/groups"]').click().trigger("mouseout")
//         cy.get('.mb-3 > a').click()
//         cy.get('#controlled-tab-example-tabpane-studentInfo > .btn-icon').click()
//         cy.get('#controlled-tab-example-tab-newstudent').click()
//         cy.get('.g-4 > :nth-child(1) > .form-control').type("sai")
//         cy.get('.g-4 > :nth-child(2) > .form-control').type("gavara")
//         cy.get('.mt-3 > :nth-child(1) > .form-control').type("saigavara@gmail.com")
//         cy.get('.mt-3 > :nth-child(2) > .form-control').type("21")
// })
// it("existing student",()=>{
//     cy.visit("https://dev02.speechpundit.com")
//     cy.wait(5000);
//     cy.get('.d-none > .btn').click()
//     cy.get('.log').click()
//     cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
//     cy.get(':nth-child(2) > .form-control').type("luckysai")
//     cy.get('[style="text-align: center;"] > .btn').type("{enter}")
//     // cy.get('[style="text-align: center;"] > .btn').click()
//     cy.get('[href="/user"]').click()
//     cy.get('[href="/user/groups"]').click().trigger("mouseout")
//     cy.get('.mb-3 > a').click()
//     cy.get('#controlled-tab-example-tabpane-studentInfo > .btn-icon').click()
//     cy.get(':nth-child(1) > :nth-child(1) > .mb-3 > .form-control').type("majjiga")
//     cy.get(':nth-child(1) > :nth-child(2) > .mb-3 > .form-control').type("lakshmi")
//     cy.get(':nth-child(2) > .col-lg-6 > .mb-3 > .form-control').type("lakshmi.majjiga@applines.com")
//     cy.get('.margin > .float-right').click()
//     cy.get('.d-flex > :nth-child(3) > .btn').click()
// })
it("get classes",()=>{
    cy.visit("https://dev02.speechpundit.com")
    cy.wait(5000);
    cy.get('.d-none > .btn').click()
    cy.get('.log').click()
    cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
    cy.get(':nth-child(2) > .form-control').type("luckysai")
    cy.get('[style="text-align: center;"] > .btn').type("{enter}")
    cy.get(':nth-child(1) > .eachItem > :nth-child(6) > .btn').click()
    // cy.go("back")
    cy.get(':nth-child(2) > .eachItem > :nth-child(6) > .btn').click()
    // cy.go("back")
    cy.get(':nth-child(3) > .eachItem > :nth-child(6) > .btn').click()
    // cy.go("back")
    cy.get(':nth-child(4) > .eachItem > :nth-child(6) > .btn').click()
    cy.get(':nth-child(5) > .eachItem > :nth-child(6) > .btn').click()
    cy.get(':nth-child(6) > .eachItem > :nth-child(6) > .btn').click()
})
})