describe("group",()=>{
    it("group",()=>{
        cy.visit("https://dev02.speechpundit.com")
        cy.wait(5000)
        cy.get(':nth-child(6) > .nav-link').click()
        cy.get(':nth-child(1) > .form-control').type("lakshmi.majjiga+coach1@applines.com")
        cy.get(':nth-child(2) > .form-control').type("luckysai")
        cy.get('[style="text-align: center;"] > .btn').click()
        cy.get('[href="/user"]').click()
        cy.get('[href="/user/groups"]').click()
        cy.get('.btn-icon > span').click()
        cy.get('#formHorizontalName').type("lakshmi")
        cy.get('#formHorizontalLevel').select("Beginner")
        // cy.get(':nth-child(3) > .col-sm-10 > .react-datepicker-wrapper > .react-datepicker__input-container > .form-control').type("9:30 AM").select()
        // cy.get(':nth-child(4) > .col-sm-10 > .react-datepicker-wrapper > .react-datepicker__input-container > .form-control').type("11:30 AM")
        // cy.wait(5000)
        // cy.get("#Mon").click()
        // cy.wait(5000)
        cy.get(':nth-child(3) > .col-sm-10 > .react-datepicker-wrapper > .react-datepicker__input-container > .form-control').click()
        cy.get('.react-datepicker__time-list > :nth-child(39)').click()
        cy.get(':nth-child(4) > .col-sm-10 > .react-datepicker-wrapper > .react-datepicker__input-container > .form-control').click()
        cy.get('.react-datepicker__time-list > :nth-child(45)').click()
        cy.get('#Mon').click()
        cy.get("#Fri").click()
        cy.get('#startDate').type("2023-09-27")
        cy.get("#enddate").type("2024-09-27")
        // cy.get("calender-widget").find(".day").contains("27").click()
        // cy.contains("28").click()
        // cy.get("#startDate").should("have.value","28/9/2023")
        cy.get('.float-right').click()
        
    })
})