# Generated by Django 2.2.12 on 2023-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
