# Generated by Django 2.2.12 on 2023-08-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
