# Generated by Django 2.2.12 on 2023-08-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table=None,
        ),
    ]
