# Generated by Django 2.2.12 on 2023-08-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230831_0750'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
    ]
