# Generated by Django 2.2.12 on 2023-08-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230831_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeType',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipeCreatedAt',
        ),
    ]
