# Generated by Django 2.2.12 on 2023-08-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20230831_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeImageUrl',
            new_name='ImageUrl',
        ),
    ]
