# Generated by Django 4.2.4 on 2023-09-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20230831_0834'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table=None,
        ),
    ]
