# Generated by Django 4.2.4 on 2023-09-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_recipe_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Type',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non-Vegetarian'), ('sweets', 'Sweets'), ('deserts', 'Deserts'), ('chocolates', 'Chocolates'), ('cookies', 'Cookies')], max_length=15),
        ),
    ]
